## 矩阵运算

### 矩阵（数组）的创建

In [3]:
import numpy as np

a = np.arange(3,10) # 默认从3开始到10（不包括10），步长为1
print(a)

a_ones = np.ones((3,4)) # 创建3*4的全1矩阵 #zeros 元素为0的函数
print(a_ones)

a_eye = np.eye(3) # 创建3阶单位矩阵
print(a_eye)

[3 4 5 6 7 8 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 矩阵求点乘
* 注意两个数组的行与列的大小要匹配
* 注意与数组的四则运算区别

In [4]:
a=np.array([[1,2,3],
            [7,6,2]])
b=np.array([[1,2],
            [7,6],
            [8,2]])
a.dot(b)

array([[39, 20],
       [65, 54]])

### 行列式的叉乘

a = np.array([[2,3],
             [6,2]])

print(np.linalg.det(a))

### 矩阵特征值求解
* 注意矩阵必须是方阵（行列大小一样）

In [6]:
a=np.array([[1,3],
            [7,2]])
k,j=np.linalg.eig(a)

In [7]:
#特征值
k

array([-3.10977223,  6.10977223])

In [8]:
#特征向量
j

array([[-0.58959436, -0.50629921],
       [ 0.80769951, -0.86235788]])

### 矩阵转置

In [9]:
a=np.array([[1,3],
            [7,2]])
a.T

array([[1, 7],
       [3, 2]])

### 矩阵的逆 a−1
* 求矩阵的逆需要先导入numpy.linalg，用linalg的inv函数来求逆。
* 矩阵求逆的条件也必须是方阵（矩阵的行数和列数相同）。

In [11]:
np.linalg.inv(a)

array([[-0.10526316,  0.15789474],
       [ 0.36842105, -0.05263158]])