## nump 切片，拼接，分裂，变形

### array的数据属性
* 维度（ndim）；形状(shape)；大小(size)
* 轴的概念——通过不同的axis，numpy会沿着不同的方向进行操作；如果axis=0，则沿着纵轴进行操作；axis=1，则沿着横轴进行操作；如果不设置，那么对所有的元素操作

In [1]:
import numpy as np
a = np.array([2,3,4,5])

#一维数组
print(a.ndim,a.shape,a.size)

1 (4,) 4


In [2]:
#二维数组可以看成多个一维数组
b=np.array([[1,2,3],[8,7,6]])
print(b)
print(b.ndim,b.shape,b.size)

[[1 2 3]
 [8 7 6]]
2 (2, 3) 6


In [3]:
b.ndim

2

In [4]:
#所谓三维数组可以看成多个二维数组，数据分析多是二维数组，高维数组并不常用
b=np.array([[[1,2],[7,6]],[[1,2],[4,5]]])
print(b)
b.ndim
print(b.ndim,b.shape,b.size)

[[[1 2]
  [7 6]]

 [[1 2]
  [4 5]]]
3 (2, 2, 2) 8


In [5]:
# 轴决定操作方向
b=np.array([[1,2],[7,6]])
print(np.sum(b),np.sum(b, axis=1),np.sum(b,axis=0))

16 [ 3 13] [8 8]


# 数组的操作
* 切片；拼接；分裂；变形

### 切片
* 第一个位置是0号位；
* 包含起点包含终点；
* : 代表获取全部；
* 双 : 表示间隔；
* 负数为倒取；
* 视图与副本（copy）

In [6]:
b = np.array([[1,2,0,3],[4,7,6,1],[7,2,8,9]])
print(b)

[[1 2 0 3]
 [4 7 6 1]
 [7 2 8 9]]


In [7]:
# 对二维数组：[行 ，列]
print(b[1,2])


6


In [8]:
# #注意切片后类型的变化,一个:一维；两个:二维
print(b[0:1,1])
print(b[:,1])
print(b[2,:])
print(b[::2,1])
print(b[-2:,0:2])

[2]
[2 7 2]
[7 2 8 9]
[2 2]
[[4 7]
 [7 2]]


In [10]:
b

array([[1, 2, 0, 3],
       [4, 7, 6, 1],
       [7, 2, 8, 9]])

In [11]:
b1=b[1,2]
b1=3
print(b,b1)

[[1 2 0 3]
 [4 7 6 1]
 [7 2 8 9]] 3


In [13]:
#当截取数组的某个子数组的时候，子数组中的元素变化原来数组也发生变化，这种子数组本质是只是原数组的一个“视图”
b1=b[1:3,1:3]
b1[1,1]=100
print(b)
print(b1)

[[  1   2   0   3]
 [  4   7   6   1]
 [  7   2 100   9]]
[[  7   6]
 [  2 100]]


#### copy方法产生真正的副本
* 不应副本直接选出数组赋值，相应的，会改变原始数组

In [15]:
print(b)
b1=b[1:3,1:3].copy()
b1[1,1]=88
print(b)
print(b1)

[[  1   2   0   3]
 [  4   7   6   1]
 [  7   2 100   9]]
[[  1   2   0   3]
 [  4   7   6   1]
 [  7   2 100   9]]
[[ 7  6]
 [ 2 88]]


### 数组的拼接

In [18]:
a1=np.array([[1,3,4],[3,5,6]])
a2=np.array([[7,8,9],[2,4,1]])
a2

array([[7, 8, 9],
       [2, 4, 1]])

In [19]:
print(np.concatenate([a1,a2],axis = 0))

[[1 3 4]
 [3 5 6]
 [7 8 9]
 [2 4 1]]


In [20]:
print(np.concatenate([a1,a2],axis=1))

[[1 3 4 7 8 9]
 [3 5 6 2 4 1]]


In [21]:
#横向拼接要求更严格
a1=np.array([[1,3,4],[3,5,6]])
a2=np.array([[1,3,4],[3,5,6],[3,5,4]])
print(np.concatenate([a1,a2],axis=0))

[[1 3 4]
 [3 5 6]
 [1 3 4]
 [3 5 6]
 [3 5 4]]


### 分裂

In [24]:
#位置列表
x = [2,1,4,5,2,5,7,8]
print(x)
np.split(x,[2,4])

[2, 1, 4, 5, 2, 5, 7, 8]


[array([2, 1]), array([4, 5]), array([2, 5, 7, 8])]

In [25]:
x=np.array([[2,1,4,5],[2,1,5,7],[5,2,3,6],[7,2,7,1]])
print(x)
print(np.split(x,[2,3],axis=0))
print(np.split(x,[2,3],axis=1))

[[2 1 4 5]
 [2 1 5 7]
 [5 2 3 6]
 [7 2 7 1]]
[array([[2, 1, 4, 5],
       [2, 1, 5, 7]]), array([[5, 2, 3, 6]]), array([[7, 2, 7, 1]])]
[array([[2, 1],
       [2, 1],
       [5, 2],
       [7, 2]]), array([[4],
       [5],
       [3],
       [7]]), array([[5],
       [7],
       [6],
       [1]])]


### 变形

In [27]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
print(a.reshape(4,3))
print(a.reshape(1,12))
print(a.reshape(3,4))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
print(a.reshape(2,2,3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
