## scipy
SciPy是一款方便、易于使用、专为科学和工程设计的Python工具包.它包括统计,优化,整合,线性代数模块,傅里叶变换,信号和图像处理,常微分方程求解器等等.


## scipy的功能
特殊函数 (scipy.special)

积分 (scipy.integrate)

优化 (scipy.optimize)

插值 (scipy.interpolate)

傅立叶变换 (scipy.fftpack)

信号处理 (scipy.signal)

线性代数 (scipy.linalg)

稀疏特征值 (scipy.sparse)

统计 (scipy.stats)

多维图像处理 (scipy.ndimage)

文件 IO (scipy.io)

### optimize.leastsq 最小二次乘法求极小值函数

In [2]:
import numpy as np
from scipy import optimize
import pylab

In [3]:
x = np.array([8.23,2.72,6.39,8.71,4.7,2.0,3.78])
y = np.array([9.01,2.58,6.47,6.71,4.1,4.23,4.05])
def cc(p):
    k,b = p
    return y-(k*x+b)#注意返回的结果是一个矩阵
r = optimize.leastsq(cc,[1,0])
print(r)#0号位为拟合出来的参数，1号位如果是为小于或是等于4的整数则说明拟合成功

(array([0.72468836, 1.52530491]), 2)


### 直角坐标下取bins
当曲线点的波动非常大时（比如有周期性波动），此时取bins能比较好的观察整体规律
* np.linspace
* np.histogram

In [5]:
#均匀选取确定范围内的n个值
np.linspace(2,6.3,10)

array([2.        , 2.47777778, 2.95555556, 3.43333333, 3.91111111,
       4.38888889, 4.86666667, 5.34444444, 5.82222222, 6.3       ])

In [6]:
a=np.array([2,1,3,4,6,2,1])
bins=np.linspace(1,6,3) # 在1-6之间取3个数1,3.5（均值）,6 
bins

array([1. , 3.5, 6. ])

In [7]:
np.histogram(a,bins)#histogram会计算区间之间的满足条件的数据个数，结果中0号位为统计结果，1号位为对应的区间

(array([5, 2], dtype=int64), array([1. , 3.5, 6. ]))