# python 优点
    * 变量不需预定义类型；
    * 变量类型可变；
    * 列表字典等数据结构动能强大——其元素可以是任意类型变量。
  
# python缺点
    * 列表的嵌套实际上能构建出各种需要得数据结构；同时数据量增大时，会占据大量内存。
    * python不用编译，并不是因为它不用翻译，而是因为它是在运行程序的时候，翻译一行执行一行。相比批量翻译然后执行，这种翻译一行执行一行的过程必然效率低下
    
# numpy 
    * 减少运算占用内存，提升运行算效率；numpy解决循环效率的思路很简单，就是用矩阵（数组）的运算函数来代替python的循环，而在numpy里，矩阵运算的函数底层都是用c或是fortran这样高效的语言来实现的。

    * numpy数组 array与list比较：
        元素类型必须一致——list的元素可以不一致
        元素类型转化顺序：整数——浮点数——(bool——)字符串
       

## 当数组中出现类型一致时，numpy会让其强行一致，按照整数——浮点数——(bool——)字符串顺序


In [1]:
import numpy as np

a = np.array([1,3,5.6])
print(a,a[0])
#数组有浮点时，整体转浮点型

[1.  3.  5.6] 1.0


In [2]:
# 赋值情况
a[0] = 8
print(a)


[8.  3.  5.6]


In [3]:

a=np.array([2,1,4,5])
a[0]=5.6
print(a)
#数组有整数时时，整体转整数型

[5 1 4 5]


In [4]:
a=np.array([1,2,4])
print(a)

[1 2 4]


In [5]:
#数组提供了定义类型的方法
np.array([2.5,4,1,4,5.2],dtype="int8")

array([2, 4, 1, 4, 5], dtype=int8)

## numpy 效率，内存

In [7]:
import sys

# 在 python 中需要循环实习

list1 = range(1,1000000)
%time list2 = [5*i for i in list1]    ##计算执行时间
print(list2[3],sys.getsizeof(list2)) ##getsizeof函数是用来监控变量的内存占用


Wall time: 165 ms
20 8697464


In [8]:
# numpy
list_numpy = np.array(range(1,1000000))
%time list_numpy1 = list_numpy*5
print(list_numpy1[3],sys.getsizeof(list_numpy1))

Wall time: 24 ms
20 4000092
